# DO NOT DELETE: Beginning of Haskell dependencies
/home/kevin/my\ strafunski/StrategyLib/MonadicFunctions.o : StrategyLib/MonadicFunctions.hs
/home/kevin/my\ strafunski/StrategyLib/TermRep.o : StrategyLib/TermRep.hs
/home/kevin/my\ strafunski/StrategyLib/MonadMaybe.o : StrategyLib/MonadMaybe.hs
/home/kevin/my\ strafunski/StrategyLib/MonadRun.o : StrategyLib/MonadRun.hs
/home/kevin/my\ strafunski/StrategyLib/MonadRun.o : StrategyLib/MonadMaybe.hi
/home/kevin/my\ strafunski/StrategyLib/StrategyPrimitives.o : StrategyLib/StrategyPrimitives.hs
/home/kevin/my\ strafunski/StrategyLib/StrategyPrimitives.o : StrategyLib/MonadRun.hi
/home/kevin/my\ strafunski/StrategyLib/StrategyPrimitives.o : StrategyLib/MonadicFunctions.hi
/home/kevin/my\ strafunski/StrategyLib/StrategyPrimitives.o : StrategyLib/TermRep.hi
/home/kevin/my\ strafunski/StrategyLib/StrategyPrelude.o : StrategyLib/StrategyPrelude.hs
/home/kevin/my\ strafunski/StrategyLib/StrategyPrelude.o : StrategyLib/StrategyPrimitives.hi
/home/kevin/my\ strafunski/StrategyLib/OverloadingTheme.o : StrategyLib/OverloadingTheme.hs
/home/kevin/my\ strafunski/StrategyLib/OverloadingTheme.o : StrategyLib/StrategyPrelude.hi
/home/kevin/my\ strafunski/StrategyLib/StrategyInfix.o : StrategyLib/StrategyInfix.hs
/home/kevin/my\ strafunski/StrategyLib/StrategyInfix.o : StrategyLib/OverloadingTheme.hi
/home/kevin/my\ strafunski/StrategyLib/StrategyInfix.o : StrategyLib/StrategyPrelude.hi
/home/kevin/my\ strafunski/StrategyLib/FlowTheme.o : StrategyLib/FlowTheme.hs
/home/kevin/my\ strafunski/StrategyLib/FlowTheme.o : StrategyLib/OverloadingTheme.hi
/home/kevin/my\ strafunski/StrategyLib/FlowTheme.o : StrategyLib/StrategyPrelude.hi
/home/kevin/my\ strafunski/StrategyLib/TraversalTheme.o : StrategyLib/TraversalTheme.hs
/home/kevin/my\ strafunski/StrategyLib/TraversalTheme.o : StrategyLib/FlowTheme.hi
/home/kevin/my\ strafunski/StrategyLib/TraversalTheme.o : StrategyLib/OverloadingTheme.hi
/home/kevin/my\ strafunski/StrategyLib/TraversalTheme.o : StrategyLib/StrategyPrelude.hi
/home/kevin/my\ strafunski/StrategyLib/FixpointTheme.o : StrategyLib/FixpointTheme.hs
/home/kevin/my\ strafunski/StrategyLib/FixpointTheme.o : StrategyLib/TraversalTheme.hi
/home/kevin/my\ strafunski/StrategyLib/FixpointTheme.o : StrategyLib/FlowTheme.hi
/home/kevin/my\ strafunski/StrategyLib/FixpointTheme.o : StrategyLib/StrategyPrelude.hi
/home/kevin/my\ strafunski/StrategyLib/NameTheme.o : StrategyLib/NameTheme.hs
/home/kevin/my\ strafunski/StrategyLib/NameTheme.o : StrategyLib/TraversalTheme.hi
/home/kevin/my\ strafunski/StrategyLib/NameTheme.o : StrategyLib/FlowTheme.hi
/home/kevin/my\ strafunski/StrategyLib/NameTheme.o : StrategyLib/OverloadingTheme.hi
/home/kevin/my\ strafunski/StrategyLib/NameTheme.o : StrategyLib/StrategyPrelude.hi
/home/kevin/my\ strafunski/StrategyLib/PathTheme.o : StrategyLib/PathTheme.hs
/home/kevin/my\ strafunski/StrategyLib/PathTheme.o : StrategyLib/TraversalTheme.hi
/home/kevin/my\ strafunski/StrategyLib/PathTheme.o : StrategyLib/FlowTheme.hi
/home/kevin/my\ strafunski/StrategyLib/PathTheme.o : StrategyLib/OverloadingTheme.hi
/home/kevin/my\ strafunski/StrategyLib/PathTheme.o : StrategyLib/StrategyPrelude.hi
/home/kevin/my\ strafunski/StrategyLib/KeyholeTheme.o : StrategyLib/KeyholeTheme.hs
/home/kevin/my\ strafunski/StrategyLib/KeyholeTheme.o : StrategyLib/TraversalTheme.hi
/home/kevin/my\ strafunski/StrategyLib/KeyholeTheme.o : StrategyLib/FlowTheme.hi
/home/kevin/my\ strafunski/StrategyLib/KeyholeTheme.o : StrategyLib/PathTheme.hi
/home/kevin/my\ strafunski/StrategyLib/KeyholeTheme.o : StrategyLib/OverloadingTheme.hi
/home/kevin/my\ strafunski/StrategyLib/KeyholeTheme.o : StrategyLib/StrategyPrelude.hi
/home/kevin/my\ strafunski/StrategyLib/KeyholeTheme.o : StrategyLib/MonadicFunctions.hi
/home/kevin/my\ strafunski/StrategyLib/EffectTheme.o : StrategyLib/EffectTheme.hs
/home/kevin/my\ strafunski/StrategyLib/EffectTheme.o : StrategyLib/StrategyPrimitives.hi
/home/kevin/my\ strafunski/StrategyLib/EffectTheme.o : StrategyLib/OverloadingTheme.hi
/home/kevin/my\ strafunski/StrategyLib/EffectTheme.o : StrategyLib/StrategyPrelude.hi
/home/kevin/my\ strafunski/StrategyLib/EffectTheme.o : StrategyLib/MonadRun.hi
/home/kevin/my\ strafunski/StrategyLib/ContainerTheme.o : StrategyLib/ContainerTheme.hs
/home/kevin/my\ strafunski/StrategyLib/ContainerTheme.o : StrategyLib/StrategyPrelude.hi
/home/kevin/my\ strafunski/StrategyLib/RefactoringTheme.o : StrategyLib/RefactoringTheme.hs
/home/kevin/my\ strafunski/StrategyLib/RefactoringTheme.o : StrategyLib/NameTheme.hi
/home/kevin/my\ strafunski/StrategyLib/RefactoringTheme.o : StrategyLib/KeyholeTheme.hi
/home/kevin/my\ strafunski/StrategyLib/RefactoringTheme.o : StrategyLib/StrategyPrelude.hi
/home/kevin/my\ strafunski/StrategyLib/MetricsTheme.o : StrategyLib/MetricsTheme.hs
/home/kevin/my\ strafunski/StrategyLib/MetricsTheme.o : StrategyLib/FlowTheme.hi
/home/kevin/my\ strafunski/StrategyLib/MetricsTheme.o : StrategyLib/OverloadingTheme.hi
/home/kevin/my\ strafunski/StrategyLib/MetricsTheme.o : StrategyLib/StrategyPrelude.hi
/home/kevin/my\ strafunski/StrategyLib/MoreMonoids.o : StrategyLib/MoreMonoids.hs
/home/kevin/my\ strafunski/StrategyLib/StrategyLib.o : StrategyLib/StrategyLib.hs
/home/kevin/my\ strafunski/StrategyLib/StrategyLib.o : StrategyLib/MetricsTheme.hi
/home/kevin/my\ strafunski/StrategyLib/StrategyLib.o : StrategyLib/RefactoringTheme.hi
/home/kevin/my\ strafunski/StrategyLib/StrategyLib.o : StrategyLib/TraversalTheme.hi
/home/kevin/my\ strafunski/StrategyLib/StrategyLib.o : StrategyLib/FlowTheme.hi
/home/kevin/my\ strafunski/StrategyLib/StrategyLib.o : StrategyLib/ContainerTheme.hi
/home/kevin/my\ strafunski/StrategyLib/StrategyLib.o : StrategyLib/EffectTheme.hi
/home/kevin/my\ strafunski/StrategyLib/StrategyLib.o : StrategyLib/KeyholeTheme.hi
/home/kevin/my\ strafunski/StrategyLib/StrategyLib.o : StrategyLib/NameTheme.hi
/home/kevin/my\ strafunski/StrategyLib/StrategyLib.o : StrategyLib/PathTheme.hi
/home/kevin/my\ strafunski/StrategyLib/StrategyLib.o : StrategyLib/FixpointTheme.hi
/home/kevin/my\ strafunski/StrategyLib/StrategyLib.o : StrategyLib/OverloadingTheme.hi
/home/kevin/my\ strafunski/StrategyLib/StrategyLib.o : StrategyLib/StrategyInfix.hi
/home/kevin/my\ strafunski/StrategyLib/StrategyLib.o : StrategyLib/StrategyPrelude.hi
/home/kevin/my\ strafunski/StrategyLib/StrategyLib.o : StrategyLib/MoreMonoids.hi
/home/kevin/my\ strafunski/StrategyLib/StrategyLib.o : StrategyLib/MonadMaybe.hi
Main.o : Main.hs
Main.o : StrategyLib/StrategyLib.hi
# DO NOT DELETE: End of Haskell dependencies
